
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
#spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
server:  port: ${PORT:0}
  
spring:  datasource:    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
      jpa:    hibernate:      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  application:    name: book-microservice-dev
    
eureka:
  client:
    service-url:
         defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    
springdoc:  api-docs:    path: /bookapi-docs
  swagger-ui:    path: /swagger-ui-bookapi.html    operations-sorter: method
    
